### ISSUE TITLE
error about the fuction——CHETAHclassifier

### ISSUE THREAD

**Issue by by-young** [jdekanter/CHETAH#8]
Error in ref_profiles[genes, type, drop = FALSE] : 
  subscript out of bounds

when I run the function CHETAHclassifier:
out1 <- CHETAHclassifier(input = input_test, ref_cells = liver_ref)

the output:
Preparing data....    

Running analysis... 

Error in ref_profiles[genes, type, drop = FALSE] : 
  subscript out of bounds

so what is wrong here? And how should I deal with it?

**Comment by by-young** [comment]
dear author:
    I have known the reason of the error I met above.  It is because the number of the overlap gene between ref and test  is too small.


and i also face another problem that your tool cannot deal with the binary classification. When we use the ref only contains two types of cell, the CHETAHclassifier function cannot work.

**Comment by jdekanter** [comment]
Dear by-young,

Thank you for your message, and your very useful insight! I will soon add a specific error message for when the overlap of genes is too low or non-existent, that was an big oversight on my part. 

It is also true that the method currently can't handle a classification with only two cell types, simply because it is not possible to build a dendrogram out of two variables. I have not thought about this for a while, but it has to be possible to implement this. Excuse me for not mentioning this explicitly. I will add this in the vignette and on Github.
